### ISSUE TITLE
Panel Icons Blury

### ISSUE THREAD

**Issue by Foggalong** [ozonos/ozon-shell-theme#10]
With shell theme
![screenshot from 2014-12-06 19 06 05](https://cloud.githubusercontent.com/assets/5920259/5328534/08452d24-7d7b-11e4-8aac-8d51fc4ea7c6.png)

Without shell theme
![screenshot from 2014-12-06 19 06 01](https://cloud.githubusercontent.com/assets/5920259/5328535/084acb8a-7d7b-11e4-9ef8-4a83d7507f11.png)

**Comment by me4oslav** [comment]
Fixed.
